services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    start: npm run start
    ports:
      - "80:80"
    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/kanban_db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban_db
      JWT_SECRET_KEY: hello263873
